export const USER_ROLES = {
  STUDENT: "STUDENT",
  RECRUITER: "RECRUITER"
};

export const APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  SHORTLISTED: "SHORTLISTED",
  REJECTED: "REJECTED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  OFFERED: "OFFERED",
  HIRED: "HIRED"
};

export const SLOT_STATUS = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
  CANCELLED: "CANCELLED"
};